# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/tolga/Desktop/lab11_vivado/question1/Basys-3-Master.xdc

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_bouncer_design_wrapp_0_0/design_1_bouncer_design_wrapp_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_bouncer_design_wrapp_0_0 || ORIG_REF_NAME==design_1_bouncer_design_wrapp_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xup_clk_divider_0_0/design_1_xup_clk_divider_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xup_clk_divider_0_0 || ORIG_REF_NAME==design_1_xup_clk_divider_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xup_dff_en_reset_0_0/design_1_xup_dff_en_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xup_dff_en_reset_0_0 || ORIG_REF_NAME==design_1_xup_dff_en_reset_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_A_0/design_1_A_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_A_0 || ORIG_REF_NAME==design_1_A_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xup_inv_0_0/design_1_xup_inv_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xup_inv_0_0 || ORIG_REF_NAME==design_1_xup_inv_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xup_and2_0_0/design_1_xup_and2_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xup_and2_0_0 || ORIG_REF_NAME==design_1_xup_and2_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xup_and2_1_0/design_1_xup_and2_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xup_and2_1_0 || ORIG_REF_NAME==design_1_xup_and2_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xup_and2_2_0/design_1_xup_and2_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xup_and2_2_0 || ORIG_REF_NAME==design_1_xup_and2_2_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xup_and2_3_0/design_1_xup_and2_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xup_and2_3_0 || ORIG_REF_NAME==design_1_xup_and2_3_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xup_and3_0_0/design_1_xup_and3_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xup_and3_0_0 || ORIG_REF_NAME==design_1_xup_and3_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xup_inv_1_0/design_1_xup_inv_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xup_inv_1_0 || ORIG_REF_NAME==design_1_xup_inv_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xup_inv_2_0/design_1_xup_inv_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xup_inv_2_0 || ORIG_REF_NAME==design_1_xup_inv_2_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xup_or2_0_0/design_1_xup_or2_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xup_or2_0_0 || ORIG_REF_NAME==design_1_xup_or2_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xup_or3_0_0/design_1_xup_or3_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xup_or3_0_0 || ORIG_REF_NAME==design_1_xup_or3_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xup_and3_1_0/design_1_xup_and3_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xup_and3_1_0 || ORIG_REF_NAME==design_1_xup_and3_1_0} -quiet] -quiet

# XDC: c:/Users/tolga/Desktop/lab11_vivado/question1/question1.gen/sources_1/bd/design_1/design_1_ooc.xdc
