# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/tolga/Desktop/ee213_lab10/question_2/question_2.srcs/sources_1/bd/question2_design/ip/question2_design_c_counter_binary_0_0/question2_design_c_counter_binary_0_0.xci
# IP: The module: 'question2_design_c_counter_binary_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/tolga/Desktop/ee213_lab10/question_2/question_2.gen/sources_1/bd/question2_design/ip/question2_design_c_counter_binary_0_0/question2_design_c_counter_binary_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'question2_design_c_counter_binary_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/tolga/Desktop/ee213_lab10/question_2/question_2.srcs/sources_1/bd/question2_design/ip/question2_design_c_counter_binary_0_0/question2_design_c_counter_binary_0_0.xci
# IP: The module: 'question2_design_c_counter_binary_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/tolga/Desktop/ee213_lab10/question_2/question_2.gen/sources_1/bd/question2_design/ip/question2_design_c_counter_binary_0_0/question2_design_c_counter_binary_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'question2_design_c_counter_binary_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
