# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/tolga/Desktop/ee213_lab10/question_2/Basys-3-Master.xdc

# Block Designs: bd/question2_design/question2_design.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==question2_design || ORIG_REF_NAME==question2_design} -quiet] -quiet

# IP: bd/question2_design/ip/question2_design_bin2bcd_0_1/question2_design_bin2bcd_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==question2_design_bin2bcd_0_1 || ORIG_REF_NAME==question2_design_bin2bcd_0_1} -quiet] -quiet

# IP: bd/question2_design/ip/question2_design_xlconcat_0_0/question2_design_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==question2_design_xlconcat_0_0 || ORIG_REF_NAME==question2_design_xlconcat_0_0} -quiet] -quiet

# IP: bd/question2_design/ip/question2_design_xlconcat_1_0/question2_design_xlconcat_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==question2_design_xlconcat_1_0 || ORIG_REF_NAME==question2_design_xlconcat_1_0} -quiet] -quiet

# IP: bd/question2_design/ip/question2_design_xup_clk_divider_0_0/question2_design_xup_clk_divider_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==question2_design_xup_clk_divider_0_0 || ORIG_REF_NAME==question2_design_xup_clk_divider_0_0} -quiet] -quiet

# IP: bd/question2_design/ip/question2_design_c_counter_binary_0_0/question2_design_c_counter_binary_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==question2_design_c_counter_binary_0_0 || ORIG_REF_NAME==question2_design_c_counter_binary_0_0} -quiet] -quiet

# IP: bd/question2_design/ip/question2_design_bin2bcd_1_0/question2_design_bin2bcd_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==question2_design_bin2bcd_1_0 || ORIG_REF_NAME==question2_design_bin2bcd_1_0} -quiet] -quiet

# IP: bd/question2_design/ip/question2_design_xlconcat_2_0/question2_design_xlconcat_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==question2_design_xlconcat_2_0 || ORIG_REF_NAME==question2_design_xlconcat_2_0} -quiet] -quiet

# IP: bd/question2_design/ip/question2_design_xup_2_to_1_mux_vector_0_0/question2_design_xup_2_to_1_mux_vector_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==question2_design_xup_2_to_1_mux_vector_0_0 || ORIG_REF_NAME==question2_design_xup_2_to_1_mux_vector_0_0} -quiet] -quiet

# IP: bd/question2_design/ip/question2_design_seg7display_0_0/question2_design_seg7display_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==question2_design_seg7display_0_0 || ORIG_REF_NAME==question2_design_seg7display_0_0} -quiet] -quiet

# IP: bd/question2_design/ip/question2_design_xlconcat_3_0/question2_design_xlconcat_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==question2_design_xlconcat_3_0 || ORIG_REF_NAME==question2_design_xlconcat_3_0} -quiet] -quiet

# IP: bd/question2_design/ip/question2_design_xlconstant_0_0/question2_design_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==question2_design_xlconstant_0_0 || ORIG_REF_NAME==question2_design_xlconstant_0_0} -quiet] -quiet

# XDC: c:/Users/tolga/Desktop/ee213_lab10/question_2/question_2.gen/sources_1/bd/question2_design/question2_design_ooc.xdc
