# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/tolga/Desktop/Projects/vivado/lab_6/Basys-3-Master 2.xdc

# Block Designs: bd/root_1/root_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==root_1 || ORIG_REF_NAME==root_1} -quiet] -quiet

# IP: bd/root_1/ip/root_1_question_a_0_0/root_1_question_a_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==root_1_question_a_0_0 || ORIG_REF_NAME==root_1_question_a_0_0} -quiet] -quiet

# IP: bd/root_1/ip/root_1_question_a_0_1/root_1_question_a_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==root_1_question_a_0_1 || ORIG_REF_NAME==root_1_question_a_0_1} -quiet] -quiet

# IP: bd/root_1/ip/root_1_xup_inv_0_0/root_1_xup_inv_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==root_1_xup_inv_0_0 || ORIG_REF_NAME==root_1_xup_inv_0_0} -quiet] -quiet

# XDC: c:/Users/tolga/Desktop/Projects/vivado/lab_6/lab_6_main/lab_6_main.gen/sources_1/bd/root_1/root_1_ooc.xdc
