# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/tolga/Desktop/vivado_final/final/Basys-3-Master.xdc

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xup_dff_0_0/design_1_xup_dff_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xup_dff_0_0 || ORIG_REF_NAME==design_1_xup_dff_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xup_clk_divider_0_0/design_1_xup_clk_divider_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xup_clk_divider_0_0 || ORIG_REF_NAME==design_1_xup_clk_divider_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xup_dff_0_1/design_1_xup_dff_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xup_dff_0_1 || ORIG_REF_NAME==design_1_xup_dff_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xup_and2_0_0/design_1_xup_and2_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xup_and2_0_0 || ORIG_REF_NAME==design_1_xup_and2_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xup_inv_0_0/design_1_xup_inv_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xup_inv_0_0 || ORIG_REF_NAME==design_1_xup_inv_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xup_and2_1_0/design_1_xup_and2_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xup_and2_1_0 || ORIG_REF_NAME==design_1_xup_and2_1_0} -quiet] -quiet

# XDC: c:/Users/tolga/Desktop/vivado_final/final/final.gen/sources_1/bd/design_1/design_1_ooc.xdc
