# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/tolga/Desktop/vivado_test/lab_9/Basys-3-Master.xdc

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xup_inv_0_0/design_1_xup_inv_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xup_inv_0_0 || ORIG_REF_NAME==design_1_xup_inv_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xup_inv_0_1/design_1_xup_inv_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xup_inv_0_1 || ORIG_REF_NAME==design_1_xup_inv_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xup_inv_1_0/design_1_xup_inv_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xup_inv_1_0 || ORIG_REF_NAME==design_1_xup_inv_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xup_inv_2_0/design_1_xup_inv_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xup_inv_2_0 || ORIG_REF_NAME==design_1_xup_inv_2_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xup_and3_0_3/design_1_xup_and3_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xup_and3_0_3 || ORIG_REF_NAME==design_1_xup_and3_0_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xup_and3_0_4/design_1_xup_and3_0_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xup_and3_0_4 || ORIG_REF_NAME==design_1_xup_and3_0_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xup_and3_1_0/design_1_xup_and3_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xup_and3_1_0 || ORIG_REF_NAME==design_1_xup_and3_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xup_and3_2_1/design_1_xup_and3_2_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xup_and3_2_1 || ORIG_REF_NAME==design_1_xup_and3_2_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xup_and4_0_1/design_1_xup_and4_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xup_and4_0_1 || ORIG_REF_NAME==design_1_xup_and4_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xup_or5_0_2/design_1_xup_or5_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xup_or5_0_2 || ORIG_REF_NAME==design_1_xup_or5_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xup_and2_0_1/design_1_xup_and2_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xup_and2_0_1 || ORIG_REF_NAME==design_1_xup_and2_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xup_and3_1_1/design_1_xup_and3_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xup_and3_1_1 || ORIG_REF_NAME==design_1_xup_and3_1_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xup_or2_0_0/design_1_xup_or2_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xup_or2_0_0 || ORIG_REF_NAME==design_1_xup_or2_0_0} -quiet] -quiet

# XDC: c:/Users/tolga/Desktop/vivado_test/lab_9/lab_9.gen/sources_1/bd/design_1/design_1_ooc.xdc
