# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/tolga/Desktop/Projects/vivado/lab_6/Basys-3-Master.xdc

# Block Designs: bd/block_1/block_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==block_1 || ORIG_REF_NAME==block_1} -quiet] -quiet

# IP: bd/block_1/ip/block_1_xup_and3_0_0/block_1_xup_and3_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==block_1_xup_and3_0_0 || ORIG_REF_NAME==block_1_xup_and3_0_0} -quiet] -quiet

# IP: bd/block_1/ip/block_1_xup_and3_0_1/block_1_xup_and3_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==block_1_xup_and3_0_1 || ORIG_REF_NAME==block_1_xup_and3_0_1} -quiet] -quiet

# IP: bd/block_1/ip/block_1_xup_and3_0_2/block_1_xup_and3_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==block_1_xup_and3_0_2 || ORIG_REF_NAME==block_1_xup_and3_0_2} -quiet] -quiet

# IP: bd/block_1/ip/block_1_xup_and3_2_0/block_1_xup_and3_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==block_1_xup_and3_2_0 || ORIG_REF_NAME==block_1_xup_and3_2_0} -quiet] -quiet

# IP: bd/block_1/ip/block_1_xup_inv_0_0/block_1_xup_inv_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==block_1_xup_inv_0_0 || ORIG_REF_NAME==block_1_xup_inv_0_0} -quiet] -quiet

# IP: bd/block_1/ip/block_1_xup_inv_0_1/block_1_xup_inv_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==block_1_xup_inv_0_1 || ORIG_REF_NAME==block_1_xup_inv_0_1} -quiet] -quiet

# XDC: c:/Users/tolga/Desktop/Projects/vivado/lab_6/lab_6_ip/lab_6_ip.gen/sources_1/bd/block_1/block_1_ooc.xdc
