# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/tolga/Desktop/Projects/vivado/lab_6/lab_6_main/lab_6_main.srcs/sources_1/bd/root_1/ip/root_1_question_a_0_1/root_1_question_a_0_1.xci
# IP: The module: 'root_1_question_a_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/tolga/Desktop/Projects/vivado/lab_6/lab_6_main/lab_6_main.gen/sources_1/bd/root_1/ip/root_1_question_a_0_1/sources_1/bd/block_1/ip/block_1_xup_and3_2_0/block_1_xup_and3_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==block_1_xup_and3_2_0 || ORIG_REF_NAME==block_1_xup_and3_2_0} -quiet] -quiet

# IP: c:/Users/tolga/Desktop/Projects/vivado/lab_6/lab_6_main/lab_6_main.gen/sources_1/bd/root_1/ip/root_1_question_a_0_1/sources_1/bd/block_1/ip/block_1_xup_inv_0_1/block_1_xup_inv_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==block_1_xup_inv_0_1 || ORIG_REF_NAME==block_1_xup_inv_0_1} -quiet] -quiet

# IP: c:/Users/tolga/Desktop/Projects/vivado/lab_6/lab_6_main/lab_6_main.gen/sources_1/bd/root_1/ip/root_1_question_a_0_1/sources_1/bd/block_1/ip/block_1_xup_inv_0_0/block_1_xup_inv_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==block_1_xup_inv_0_0 || ORIG_REF_NAME==block_1_xup_inv_0_0} -quiet] -quiet

# IP: c:/Users/tolga/Desktop/Projects/vivado/lab_6/lab_6_main/lab_6_main.gen/sources_1/bd/root_1/ip/root_1_question_a_0_1/sources_1/bd/block_1/ip/block_1_xup_and3_0_2/block_1_xup_and3_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==block_1_xup_and3_0_2 || ORIG_REF_NAME==block_1_xup_and3_0_2} -quiet] -quiet

# IP: c:/Users/tolga/Desktop/Projects/vivado/lab_6/lab_6_main/lab_6_main.gen/sources_1/bd/root_1/ip/root_1_question_a_0_1/sources_1/bd/block_1/ip/block_1_xup_and3_0_1/block_1_xup_and3_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==block_1_xup_and3_0_1 || ORIG_REF_NAME==block_1_xup_and3_0_1} -quiet] -quiet

# IP: c:/Users/tolga/Desktop/Projects/vivado/lab_6/lab_6_main/lab_6_main.gen/sources_1/bd/root_1/ip/root_1_question_a_0_1/sources_1/bd/block_1/ip/block_1_xup_and3_0_0/block_1_xup_and3_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==block_1_xup_and3_0_0 || ORIG_REF_NAME==block_1_xup_and3_0_0} -quiet] -quiet

# XDC: c:/Users/tolga/Desktop/Projects/vivado/lab_6/lab_6_main/lab_6_main.gen/sources_1/bd/root_1/ip/root_1_question_a_0_1/src/Basys-3-Master.xdc
# XDC: The top module name and the constraint reference have the same name: 'root_1_question_a_0_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/tolga/Desktop/Projects/vivado/lab_6/lab_6_main/lab_6_main.gen/sources_1/bd/root_1/ip/root_1_question_a_0_1/src/block_1_ooc.xdc

# IP: c:/Users/tolga/Desktop/Projects/vivado/lab_6/lab_6_main/lab_6_main.srcs/sources_1/bd/root_1/ip/root_1_question_a_0_1/root_1_question_a_0_1.xci
# IP: The module: 'root_1_question_a_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/tolga/Desktop/Projects/vivado/lab_6/lab_6_main/lab_6_main.gen/sources_1/bd/root_1/ip/root_1_question_a_0_1/sources_1/bd/block_1/ip/block_1_xup_and3_2_0/block_1_xup_and3_2_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==block_1_xup_and3_2_0 || ORIG_REF_NAME==block_1_xup_and3_2_0} -quiet] -quiet

# IP: c:/Users/tolga/Desktop/Projects/vivado/lab_6/lab_6_main/lab_6_main.gen/sources_1/bd/root_1/ip/root_1_question_a_0_1/sources_1/bd/block_1/ip/block_1_xup_inv_0_1/block_1_xup_inv_0_1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==block_1_xup_inv_0_1 || ORIG_REF_NAME==block_1_xup_inv_0_1} -quiet] -quiet

# IP: c:/Users/tolga/Desktop/Projects/vivado/lab_6/lab_6_main/lab_6_main.gen/sources_1/bd/root_1/ip/root_1_question_a_0_1/sources_1/bd/block_1/ip/block_1_xup_inv_0_0/block_1_xup_inv_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==block_1_xup_inv_0_0 || ORIG_REF_NAME==block_1_xup_inv_0_0} -quiet] -quiet

# IP: c:/Users/tolga/Desktop/Projects/vivado/lab_6/lab_6_main/lab_6_main.gen/sources_1/bd/root_1/ip/root_1_question_a_0_1/sources_1/bd/block_1/ip/block_1_xup_and3_0_2/block_1_xup_and3_0_2.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==block_1_xup_and3_0_2 || ORIG_REF_NAME==block_1_xup_and3_0_2} -quiet] -quiet

# IP: c:/Users/tolga/Desktop/Projects/vivado/lab_6/lab_6_main/lab_6_main.gen/sources_1/bd/root_1/ip/root_1_question_a_0_1/sources_1/bd/block_1/ip/block_1_xup_and3_0_1/block_1_xup_and3_0_1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==block_1_xup_and3_0_1 || ORIG_REF_NAME==block_1_xup_and3_0_1} -quiet] -quiet

# IP: c:/Users/tolga/Desktop/Projects/vivado/lab_6/lab_6_main/lab_6_main.gen/sources_1/bd/root_1/ip/root_1_question_a_0_1/sources_1/bd/block_1/ip/block_1_xup_and3_0_0/block_1_xup_and3_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==block_1_xup_and3_0_0 || ORIG_REF_NAME==block_1_xup_and3_0_0} -quiet] -quiet

# XDC: c:/Users/tolga/Desktop/Projects/vivado/lab_6/lab_6_main/lab_6_main.gen/sources_1/bd/root_1/ip/root_1_question_a_0_1/src/Basys-3-Master.xdc
# XDC: The top module name and the constraint reference have the same name: 'root_1_question_a_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/tolga/Desktop/Projects/vivado/lab_6/lab_6_main/lab_6_main.gen/sources_1/bd/root_1/ip/root_1_question_a_0_1/src/block_1_ooc.xdc
