# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/tolga/Desktop/Projects/vivado/lab_4/Basys-3-Master.xdc

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xup_nor2_0_0/design_1_xup_nor2_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xup_nor2_0_0 || ORIG_REF_NAME==design_1_xup_nor2_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xup_nand2_0_0/design_1_xup_nand2_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xup_nand2_0_0 || ORIG_REF_NAME==design_1_xup_nand2_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xup_and3_0_0/design_1_xup_and3_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xup_and3_0_0 || ORIG_REF_NAME==design_1_xup_and3_0_0} -quiet] -quiet

# XDC: c:/Users/tolga/Desktop/Projects/vivado/lab_4/lab_4/lab_4.gen/sources_1/bd/design_1/design_1_ooc.xdc
