# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/bouncer_design/bouncer_design.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bouncer_design || ORIG_REF_NAME==bouncer_design} -quiet] -quiet

# IP: bd/bouncer_design/ip/bouncer_design_xup_dff_en_reset_0_0/bouncer_design_xup_dff_en_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bouncer_design_xup_dff_en_reset_0_0 || ORIG_REF_NAME==bouncer_design_xup_dff_en_reset_0_0} -quiet] -quiet

# IP: bd/bouncer_design/ip/bouncer_design_xup_or2_0_0/bouncer_design_xup_or2_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bouncer_design_xup_or2_0_0 || ORIG_REF_NAME==bouncer_design_xup_or2_0_0} -quiet] -quiet

# IP: bd/bouncer_design/ip/bouncer_design_xup_xor2_0_0/bouncer_design_xup_xor2_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bouncer_design_xup_xor2_0_0 || ORIG_REF_NAME==bouncer_design_xup_xor2_0_0} -quiet] -quiet

# IP: bd/bouncer_design/ip/bouncer_design_xup_xor2_0_1/bouncer_design_xup_xor2_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bouncer_design_xup_xor2_0_1 || ORIG_REF_NAME==bouncer_design_xup_xor2_0_1} -quiet] -quiet

# IP: bd/bouncer_design/ip/bouncer_design_xup_dff_en_0_0/bouncer_design_xup_dff_en_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bouncer_design_xup_dff_en_0_0 || ORIG_REF_NAME==bouncer_design_xup_dff_en_0_0} -quiet] -quiet

# IP: bd/bouncer_design/ip/bouncer_design_xup_dff_en_0_1/bouncer_design_xup_dff_en_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bouncer_design_xup_dff_en_0_1 || ORIG_REF_NAME==bouncer_design_xup_dff_en_0_1} -quiet] -quiet

# XDC: c:/Users/tolga/Desktop/lab11_vivado/bouncer/bouncer.gen/sources_1/bd/bouncer_design/bouncer_design_ooc.xdc
