# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/tolga/Desktop/ee213_lab10/question_1/Basys-3-Master.xdc

# Block Designs: bd/question1_design/question1_design.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==question1_design || ORIG_REF_NAME==question1_design} -quiet] -quiet

# IP: bd/question1_design/ip/question1_design_seg7display_0_0/question1_design_seg7display_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==question1_design_seg7display_0_0 || ORIG_REF_NAME==question1_design_seg7display_0_0} -quiet] -quiet

# IP: bd/question1_design/ip/question1_design_xlconcat_0_2/question1_design_xlconcat_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==question1_design_xlconcat_0_2 || ORIG_REF_NAME==question1_design_xlconcat_0_2} -quiet] -quiet

# IP: bd/question1_design/ip/question1_design_bin2bcd_0_0/question1_design_bin2bcd_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==question1_design_bin2bcd_0_0 || ORIG_REF_NAME==question1_design_bin2bcd_0_0} -quiet] -quiet

# IP: bd/question1_design/ip/question1_design_xlconcat_1_0/question1_design_xlconcat_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==question1_design_xlconcat_1_0 || ORIG_REF_NAME==question1_design_xlconcat_1_0} -quiet] -quiet

# IP: bd/question1_design/ip/question1_design_xlconstant_0_0/question1_design_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==question1_design_xlconstant_0_0 || ORIG_REF_NAME==question1_design_xlconstant_0_0} -quiet] -quiet

# XDC: c:/Users/tolga/Desktop/ee213_lab10/question_1/question_1.gen/sources_1/bd/question1_design/question1_design_ooc.xdc
